### ISSUE TITLE
Report more old IE / Firefox specific hacks

### ISSUE THREAD

**Issue by macbre** [macbre/analyze-css#23]
``` css
/* Everything but Internet Explorer 6  */
html>body #tres { color: red }
```

[Comprehensive List of Browser-Specific CSS Hacks](http://www.paulirish.com/2009/browser-specific-css-hacks/) by Paul Irish
