### ISSUE TITLE
Support media queries

### ISSUE THREAD

**Issue by macbre** [macbre/analyze-css#33]
``` css
@media screen and (min-width: 1370px) {
  #foo {
    color: red
  }
}
```

```
echo "@media screen and (min-width: 1370px) { #foo {} }" | DEBUG=* ./bin/analyze-css.js - -p
```
