### ISSUE TITLE
Report duplicated properties

### ISSUE THREAD

**Issue by macbre** [macbre/analyze-css#60]
Report duplicated CSS properties.

``` css
.foo {
  background:#474646;
  border:1px solid #6b6a6a;
  background:#4c4b4b;
  border:1px solid #6b6a6a;
  margin-bottom:10px;
}
```
