### ISSUE TITLE
Report the use of expression

### ISSUE THREAD

**Issue by macbre** [macbre/analyze-css#8]
``` css
p { width: expression( document.body.clientWidth > 600 ? "600px" : "auto" ); }
body { background-color: expression( (new Date()).getHours()%2 ? "#B8D4FF" : "#F08A00" ); }
```

[High Performance Web Sites: Rule 7  Avoid CSS Expressions](http://developer.yahoo.com/blogs/ydn/high-performance-sites-rule-7-avoid-css-expressions-7202.html)
