### ISSUE TITLE
Detect accidental property resets

### ISSUE THREAD

**Issue by gmetais** [macbre/analyze-css#85]
I've just read this interesting article about accidental reset:
http://css-tricks.com/accidental-css-resets/

It might be interesting to detect this kind of mistake. Or it could just be taken in account in "duplicatedProperties".

**Comment by macbre** [comment]
[MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties)

**Comment by macbre** [comment]
The example:

```css
.foo {
  background-color: red;
  background: url(images/bg.gif) no-repeat top right;
}
```

will yield:

```
.foo: "background" resets "background-color" property set earlier
```
